### PR TITLE
Updated Respone types for TS generate with scripts and workflows for it

### PR DESCRIPTION
**Pull request by Buckram123**
Updated types, so [cosmwasm-typescript-gen](https://www.npmjs.com/package/cosmwasm-typescript-gen) can generate TS types without errors. Also added example of generated types. Had two options of fixing types: wrapping return types in tuple structs or map types in `schema.rs` (like [DA0DA0 did](https://github.com/DA0-DA0/dao-contracts/blob/main/contracts/cw-core/examples/schema.rs#L37-L55)).
Have chosen wrapping types, so it's easier to maintain when we decide to change return types.

One question: what we chose for exporting `Croncat` type? 
struct: https://github.com/CronCats/cw-croncat/blob/d488c9fa017c5a2757cf59d1a4c3f88489afc840/packages/cw-croncat-core/src/msg.rs#L31-L49
generated type: 
```ts
export interface Croncat {
  Agent?: Agent | null;
  BalanceResponse?: GetBalancesResponse | null;
  ConfigResponse?: GetConfigResponse | null;
  GetAgentIdsResponse?: GetAgentIdsResponse | null;
  GetAgentResponse?: (AgentResponse | null) | null;
  GetAgentTasksResponse?: AgentTaskResponse | null;
  GetSlotHashesResponse?: GetSlotHashesResponse | null;
  GetSlotIdsResponse?: GetSlotIdsResponse | null;
  GetTaskHashResponse?: string | null;
  GetTaskResponse?: (TaskResponse | null) | null;
  GetTasksByOwnerResponse?: TaskResponse[] | null;
  GetTasksResponse?: TaskResponse[] | null;
  Task?: Task | null;
  TaskRequest?: TaskRequest | null;
  TaskResponse?: TaskResponse | null;
  ValidateIntervalResponse?: boolean | null;
  [k: string]: unknown;
}
```
enum: https://github.com/CronCats/cw-croncat/blob/d488c9fa017c5a2757cf59d1a4c3f88489afc840/packages/cw-croncat-core/src/msg.rs#L11-L28
generated type: 
```ts
export type Croncat = {
  Agent: Agent;
} | {
  Task: Task;
} | {
  ConfigResponse: GetConfigResponse;
} | {
  BalancesResponse: GetBalancesResponse;
} | {
  GetAgentIdsResponse: GetAgentIdsResponse;
} | {
  GetAgentTasksResponse: GetAgentTasksResponse;
} | {
  TaskRequest: TaskRequest;
} | {
  TaskResponse: TaskResponse;
} | {
  ValidateIntervalResponse: ValidateIntervalResponse;
} | {
  GetAgentResponse: GetAgentResponse;
} | {
  GetTasksResponse: GetTasksResponse;
} | {
  GetTasksByOwnerResponse: GetTasksByOwnerResponse;
} | {
  GetTaskResponse: GetTaskResponse;
} | {
  GetTaskHashResponse: GetTaskHashResponse;
} | {
  GetSlotHashesResponse: GetSlotHashesResponse;
} | {
  GetSlotIdsResponse: GetSlotIdsResponse;
};
```

### CODE REVIEW

**Comment by Buckram123** [comment]
Ok, there is one issue of using tuple structs for now.. https://github.com/CosmWasm/serde-json-wasm/blob/main/src/ser/mod.rs#L381

**Comment by Buckram123** [comment]
Fixed issue I mentioned above, and added tests for ser-de of the `CronCat` struct.

**Comment by mikedotexe** [comment]
Wow, awesome. I think I'll save this one for @TrevorJTClarke if it can wait, @Buckram123 ?

I'm not familiar with the schema and types yet

**Comment by Buckram123** [comment]
Added scripts and workflows as well

**Pull request merged**
